### ISSUE TITLE
FATAL:  database "discourse" does not exist

### ISSUE THREAD

**Issue by frdmn** [initforthe/forum2discourse#2]
Can't execute `import_vanilla` task:

```
[vagrant@precise32:/vagrant (master)]$ RAILS_ENV=production bundle exec rake forum2discourse:import_vanilla --trace

WARNING: --------------------------------------------------------------------------
You are running an old version of bundler, please update by running: gem install bundler


WARNING: --------------------------------------------------------------------------
You are running an old version of bundler, please update by running: gem install bundler

** Invoke forum2discourse:import_vanilla (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
FATAL:  database "discourse" does not exist
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activerecord-4.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:831:in `initialize'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activerecord-4.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:831:in `new'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activerecord-4.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:831:in `connect'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activerecord-4.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:548:in `initialize'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activerecord-4.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `new'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activerecord-4.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `postgresql_connection'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activerecord-4.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:440:in `new_connection'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activerecord-4.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:450:in `checkout_new_connection'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activerecord-4.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:421:in `acquire_connection'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activerecord-4.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:356:in `block in checkout'
/usr/local/rvm/rubies/ruby-2.0.0-p0-turbo/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activerecord-4.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:355:in `checkout'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activerecord-4.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
/usr/local/rvm/rubies/ruby-2.0.0-p0-turbo/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activerecord-4.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activerecord-4.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:546:in `retrieve_connection'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activerecord-4.0.3/lib/active_record/connection_handling.rb:79:in `retrieve_connection'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activerecord-4.0.3/lib/active_record/connection_handling.rb:53:in `connection'
/vagrant/lib/site_settings/db_provider.rb:61:in `table_exists?'
/vagrant/lib/site_settings/db_provider.rb:10:in `all'
/vagrant/lib/site_setting_extension.rb:121:in `block in refresh!'
/vagrant/lib/site_setting_extension.rb:117:in `synchronize'
/vagrant/lib/site_setting_extension.rb:117:in `refresh!'
/vagrant/config/initializers/05-site_settings.rb:3:in `block in <top (required)>'
/vagrant/vendor/gems/rails_multisite/lib/rails_multisite/connection_management.rb:53:in `block in each_connection'
/vagrant/vendor/gems/rails_multisite/lib/rails_multisite/connection_management.rb:51:in `each'
/vagrant/vendor/gems/rails_multisite/lib/rails_multisite/connection_management.rb:51:in `each_connection'
/vagrant/config/initializers/05-site_settings.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:223:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:223:in `block in load'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:214:in `load_dependency'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:223:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/railties-4.0.3/lib/rails/engine.rb:609:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/railties-4.0.3/lib/rails/engine.rb:608:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/railties-4.0.3/lib/rails/engine.rb:608:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/railties-4.0.3/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/railties-4.0.3/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/railties-4.0.3/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/rubies/ruby-2.0.0-p0-turbo/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
/usr/local/rvm/rubies/ruby-2.0.0-p0-turbo/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-2.0.0-p0-turbo/lib/ruby/2.0.0/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
/usr/local/rvm/rubies/ruby-2.0.0-p0-turbo/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
/usr/local/rvm/rubies/ruby-2.0.0-p0-turbo/lib/ruby/2.0.0/tsort.rb:209:in `block in each_strongly_connected_component_from'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/railties-4.0.3/lib/rails/initializable.rb:44:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/railties-4.0.3/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/rvm/rubies/ruby-2.0.0-p0-turbo/lib/ruby/2.0.0/tsort.rb:203:in `each_strongly_connected_component_from'
/usr/local/rvm/rubies/ruby-2.0.0-p0-turbo/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-2.0.0-p0-turbo/lib/ruby/2.0.0/tsort.rb:180:in `each'
/usr/local/rvm/rubies/ruby-2.0.0-p0-turbo/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-2.0.0-p0-turbo/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/railties-4.0.3/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/railties-4.0.3/lib/rails/application.rb:215:in `initialize!'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/railties-4.0.3/lib/rails/railtie/configurable.rb:30:in `method_missing'
/vagrant/config/environment.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:229:in `require'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:229:in `block in require'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:214:in `load_dependency'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:229:in `require'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/railties-4.0.3/lib/rails/application.rb:189:in `require_environment!'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/railties-4.0.3/lib/rails/application.rb:250:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/task.rb:236:in `call'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/task.rb:236:in `block in execute'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/task.rb:231:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/task.rb:231:in `execute'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.0.0-p0-turbo/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/task.rb:195:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/task.rb:195:in `invoke_prerequisites'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.0.0-p0-turbo/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/task.rb:161:in `invoke'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/application.rb:149:in `invoke_task'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/application.rb:106:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/application.rb:106:in `block in top_level'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/application.rb:100:in `top_level'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/application.rb:78:in `block in run'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/bin/ruby_noexec_wrapper:14:in `eval'
/usr/local/rvm/gems/ruby-2.0.0-p0-turbo/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => forum2discourse:import_vanilla => environment
[vagrant@precise32:/vagrant (master)]$
```

**Comment by kalleth** [comment]
have you exported a connection string per the readme?

You need to `export F2D_CONNECTION_STRING=mysql://root@127.0.0.1:3306/database_name` with a correct database connection string.

**Comment by frdmn** [comment]
@kalleth yes, of course:

```
[vagrant@precise32:/vagrant (master)]$ echo $F2D_CONNECTION_STRING
mysql://web_forums:melQSxxxxxxt2i0@127.0.0.1:3306/web_forums
[vagrant@precise32:/vagrant (master)]$
```

**Comment by frdmn** [comment]
@kalleth any idea?

**Comment by simmerz** [comment]
Forgive me for interjecting, but there is definitely a destination database available called "discourse" as per the config/database.yml?

**Comment by frdmn** [comment]
@simmerz this is the content of my `config/database.yml`:

```
[vagrant@precise32:/vagrant (master)]$ cat config/database.yml
development:
  adapter: postgresql
  database: discourse_development
  min_messages: warning
  pool: 5
  timeout: 5000
  host_names:
    ### Don't include the port number here. Change the "port" site setting instead, at /admin/site_settings.
    ### If you change this setting you will need to
    ###   - restart sidekiq if you change this setting
    ###   - rebake all to posts using: `RAILS_ENV=production bundle exec rake posts:rebake`
    - "localhost"

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  database: discourse_test
  min_messages: warning
  pool: 5
  timeout: 5000
  host_names:
    - test.localhost

# profile db is used for benchamarking using the script/bench.rb script
profile:
  adapter: postgresql
  database: discourse_profile
  min_messages: warning
  pool: 5
  timeout: 5000
  host_names:
    - "localhost"

# You may be surprised production is not here, it is sourced from application.rb using a monkey patch
# This is done for 2 reasons
#
# 1. we need to support blank settings correctly and rendering nothing in yaml/erb is a PITA
# 2. why go from object -> yaml -> object, pointless
```

I don't see any declaration of a database just called "discourse". Where does f2f gets this information from? Also, i assume the databases are working since the Discourse forum is working fine.

**Comment by simmerz** [comment]
The issue appears to be happening somewhere in lib/site_settings or config/initializers/05-site_settings.rb, which strikes me that it's not to do with the importer itself, but more to do with the discourse environment. I might be wrong, but that's what the backtrace is telling me.

**Comment by frdmn** [comment]
@simmerz Thanks for that informations! Unfortunately, i have no clue how i could solve this problem though. I'll just wait for a response from @kalleth

**Comment by kalleth** [comment]
@frdmn Sorry for the delay. I'm not primarily on this project at the moment.

I agree with @simmerz -- it looks like the problem is with your discourse environment at this stage.

Does discourse start up? Can you start it and get to a (blank, but running) discourse homepage/setup page?

**Comment by frdmn** [comment]
@kalleth What do you mean with blank page in special? I can start Discourse and use it without any problems. So i guess the discourse installation (default Vagrant installation) is fine.

**Comment by simmerz** [comment]
In production mode? This isn't an issue with this gem. It's a problem with the code that determines which database to use when RAILS_ENV=production that you've added to discourse. Look there please.

**Comment by kalleth** [comment]
@frdmn I've downloaded the latest version of the (vagrant) discourse image.

The guide prompts you to start discourse using `bundle exec rails s` which boots a rails server in development mode.

For forum2discourse to work correctly, first you need to make sure discourse will start in _production_ mode -- i.e. the command `RAILS_ENV=production bundle exec rails s` should start a discourse instance that you're able to access.

I've confirmed that attempting to boot discourse using the above command will fail with the same error you're seeing above. It's nothing to do with the forum2discourse gem -- you need to configure discourse with production configuration settings first.

There are two options you have here. First, you can attempt to run the importer in development mode by running:

`bundle exec rake forum2discourse:import_vanilla --trace`

(omitting the RAILS_ENV at the start will run the import in development mode). This is not recommended, I have not tested this, and I do not know if this will work.

Or, you can add the necessary configuration to discourse so that `RAILS_ENV=production bundle exec rails s` completes successfully. I can't help with this either, because it's a discourse configuration issue, nothing to do with this gem.
